/*
Copyright (C) THL A29 Limited, a Tencent company. All rights reserved.

SPDX-License-Identifier: Apache-2.0
*/

package testframework

import (
	"io/ioutil"
	"os"
	"path/filepath"

	"zhanghefan123/security/protocol"
)

const (
	org1Path = "wx-org1.chainmaker.org"
	org2Path = "wx-org2.chainmaker.org"
	org3Path = "wx-org3.chainmaker.org"
	org4Path = "wx-org4.chainmaker.org"
	org5Path = "wx-org5.chainmaker.org"
	org6Path = "wx-org6.chainmaker.org"
	org7Path = "wx-org7.chainmaker.org"
)

var (
	configDir   = "./config"
	configDatas []ConfigData
	// BlockchainId block chain id
	BlockchainId = "chain1"
	// NodeNums default node Nums
	NodeNums = 4
	// CoreEngines core engines
	CoreEngines = []protocol.CoreEngine{}
	// ListenAddrs listen addrs
	ListenAddrs = []string{
		"/ip4/0.0.0.0/tcp/11301",
		"/ip4/0.0.0.0/tcp/11302",
		"/ip4/0.0.0.0/tcp/11303",
		"/ip4/0.0.0.0/tcp/11304",
	}
	// Seeds seeds
	Seeds = []string{
		"/ip4/127.0.0.1/tcp/11301/p2p/QmV9wyvnGXtKauR2MV4bLndwfS4hnHkN6RhXMmEyLyRwqq",
		"/ip4/127.0.0.1/tcp/11302/p2p/QmYjXpS5RtSiScjJVxzJNUo2XdfDbSoE1BaaSQG2BWLhej",
		"/ip4/127.0.0.1/tcp/11303/p2p/QmYhNgL59EQriiojax98a8HQnB4DPqdN44eRy3RCdgbNPn",
		"/ip4/127.0.0.1/tcp/11304/p2p/Qmd6RRKw83sQrf4oZJEhuhouz48eu9BT1nLKNGqKcpD6LL",
	}
)

// InitLocalConfigs init local configs
func InitLocalConfigs() error {
	return initConfigs(configDir)
}

// RemoveLocalConfigs remove configs
func RemoveLocalConfigs() {
	os.RemoveAll(configDir)
}

//initConfigs
func initConfigs(config string) error {
	CoreEngines = make([]protocol.CoreEngine, NodeNums)
	configDatas = make([]ConfigData, 0)
	configDatas = append(configDatas, initCaConfigs()...)
	configDatas = append(configDatas, initConsensusConfigs()...)
	for _, configData := range configDatas {
		path, _ := filepath.Abs(config + string(os.PathSeparator) + configData.Path)
		innerDir := filepath.Dir(path)
		err := os.MkdirAll(innerDir, os.ModePerm)
		if err != nil {
			return err
		}
		err = ioutil.WriteFile(path, []byte(configData.Data), os.ModePerm)
		if err != nil {
			return err
		}
	}
	return nil
}

//nolint
func initCaConfigs() []ConfigData {
	return []ConfigData{
		{
			Path: org1Path + "/ca/ca.crt",
			Data: "-----BEGIN CERTIFICATE-----\nMIICsDCCAlWgAwIBAgIDDgO2MAoGCCqGSM49BAMCMIGKMQswCQYDVQQGEwJDTjEQ\nMA4GA1UECBMHQmVpamluZzEQMA4GA1UEBxMHQmVpamluZzEfMB0GA1UEChMWd3gt\nb3JnMS5jaGFpbm1ha2VyLm9yZzESMBAGA1UECxMJcm9vdC1jZXJ0MSIwIAYDVQQD\nExljYS53eC1vcmcxLmNoYWlubWFrZXIub3JnMB4XDTIxMDgwODExMTAyM1oXDTMx\nMDgwNjExMTAyM1owgYoxCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRAw\nDgYDVQQHEwdCZWlqaW5nMR8wHQYDVQQKExZ3eC1vcmcxLmNoYWlubWFrZXIub3Jn\nMRIwEAYDVQQLEwlyb290LWNlcnQxIjAgBgNVBAMTGWNhLnd4LW9yZzEuY2hhaW5t\nYWtlci5vcmcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAT+aw/8vpRlaxBhQJ1T\nnIgFF1B5DyHOU4NtKeNSMmD5T2p9m2zSTexzPtL/l8R/GOpY96ETKDVBAfRzBdMM\n2kW/o4GnMIGkMA4GA1UdDwEB/wQEAwIBpjAPBgNVHSUECDAGBgRVHSUAMA8GA1Ud\nEwEB/wQFMAMBAf8wKQYDVR0OBCIEIK90fQ3ieKsc3IuLGHiJbOPpb2JU3YEzAp5r\ne7CxygsOMEUGA1UdEQQ+MDyCDmNoYWlubWFrZXIub3Jngglsb2NhbGhvc3SCGWNh\nLnd4LW9yZzEuY2hhaW5tYWtlci5vcmeHBH8AAAEwCgYIKoZIzj0EAwIDSQAwRgIh\nANIt7Hl8iUFSPkmbC0hdgSxFHQykXnMAEjxIV4kUWfKFAiEA4qrvkb1C53GMa1uS\nJHxTX/uIlQbx2A1L3fLLVl7CGrQ=\n-----END CERTIFICATE-----",
		},
		{
			Path: org1Path + "/ca/ca.key",
			Data: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIANxWhMCAmEiNM9/NfdZwX/DnChqSIwJJe/M7rW3IQiboAoGCCqGSM49\nAwEHoUQDQgAE/msP/L6UZWsQYUCdU5yIBRdQeQ8hzlODbSnjUjJg+U9qfZts0k3s\ncz7S/5fEfxjqWPehEyg1QQH0cwXTDNpFvw==\n-----END EC PRIVATE KEY-----",
		},
		{
			Path: org2Path + "/ca/ca.crt",
			Data: "-----BEGIN CERTIFICATE-----\nMIICrzCCAlWgAwIBAgIDA3bZMAoGCCqGSM49BAMCMIGKMQswCQYDVQQGEwJDTjEQ\nMA4GA1UECBMHQmVpamluZzEQMA4GA1UEBxMHQmVpamluZzEfMB0GA1UEChMWd3gt\nb3JnMi5jaGFpbm1ha2VyLm9yZzESMBAGA1UECxMJcm9vdC1jZXJ0MSIwIAYDVQQD\nExljYS53eC1vcmcyLmNoYWlubWFrZXIub3JnMB4XDTIxMDgwODExMTAyM1oXDTMx\nMDgwNjExMTAyM1owgYoxCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRAw\nDgYDVQQHEwdCZWlqaW5nMR8wHQYDVQQKExZ3eC1vcmcyLmNoYWlubWFrZXIub3Jn\nMRIwEAYDVQQLEwlyb290LWNlcnQxIjAgBgNVBAMTGWNhLnd4LW9yZzIuY2hhaW5t\nYWtlci5vcmcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASmIsvnnfrNeolRcJmZ\n3z//R1Y+tP4a9S1o4gmRP4nC9q0j5LNzFzLrTLfrig1veGAUo4R91Sdhhk8WAjex\nGh+7o4GnMIGkMA4GA1UdDwEB/wQEAwIBpjAPBgNVHSUECDAGBgRVHSUAMA8GA1Ud\nEwEB/wQFMAMBAf8wKQYDVR0OBCIEIK2wKn07DMyXSO/IWPwn1YNoBitPxjdrB6Mk\nsvamaf6mMEUGA1UdEQQ+MDyCDmNoYWlubWFrZXIub3Jngglsb2NhbGhvc3SCGWNh\nLnd4LW9yZzIuY2hhaW5tYWtlci5vcmeHBH8AAAEwCgYIKoZIzj0EAwIDSAAwRQIh\nAJ1CHxJwRUx5pQNVTsp6iwVJFWY78wAtc4Po8pvJR8xzAiBHEZzYX7nWqgJw0MYD\nxBI2lH+s4gRvtaktYZLwjVZJHQ==\n-----END CERTIFICATE-----",
		},
		{
			Path: org2Path + "/ca/ca.key",
			Data: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIMeRyigfQuRZbjtToHRWKaufHLusnp7iXbdAOGEWB0cboAoGCCqGSM49\nAwEHoUQDQgAEpiLL5536zXqJUXCZmd8//0dWPrT+GvUtaOIJkT+JwvatI+Szcxcy\n60y364oNb3hgFKOEfdUnYYZPFgI3sRofuw==\n-----END EC PRIVATE KEY-----\n",
		},
		{
			Path: org3Path + "/ca/ca.crt",
			Data: "-----BEGIN CERTIFICATE-----\nMIICrzCCAlSgAwIBAgICeGAwCgYIKoZIzj0EAwIwgYoxCzAJBgNVBAYTAkNOMRAw\nDgYDVQQIEwdCZWlqaW5nMRAwDgYDVQQHEwdCZWlqaW5nMR8wHQYDVQQKExZ3eC1v\ncmczLmNoYWlubWFrZXIub3JnMRIwEAYDVQQLEwlyb290LWNlcnQxIjAgBgNVBAMT\nGWNhLnd4LW9yZzMuY2hhaW5tYWtlci5vcmcwHhcNMjEwODA4MTExMDIzWhcNMzEw\nODA2MTExMDIzWjCBijELMAkGA1UEBhMCQ04xEDAOBgNVBAgTB0JlaWppbmcxEDAO\nBgNVBAcTB0JlaWppbmcxHzAdBgNVBAoTFnd4LW9yZzMuY2hhaW5tYWtlci5vcmcx\nEjAQBgNVBAsTCXJvb3QtY2VydDEiMCAGA1UEAxMZY2Eud3gtb3JnMy5jaGFpbm1h\na2VyLm9yZzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJ4xEFAq1A+37VecvLnO\nsQEoqvayYEgwhzB2TuV3P9oijuWgKAtj/r8+tQW/eQF/+OPOA9C8DM5VGHam5yqV\nR6CjgacwgaQwDgYDVR0PAQH/BAQDAgGmMA8GA1UdJQQIMAYGBFUdJQAwDwYDVR0T\nAQH/BAUwAwEB/zApBgNVHQ4EIgQg5ISkKCgl9e3ocPhLd+x4Qou09tUCMehIkdN+\nTX/OqFAwRQYDVR0RBD4wPIIOY2hhaW5tYWtlci5vcmeCCWxvY2FsaG9zdIIZY2Eu\nd3gtb3JnMy5jaGFpbm1ha2VyLm9yZ4cEfwAAATAKBggqhkjOPQQDAgNJADBGAiEA\nufJgosyvzQiA0icry11wZTiX0BwiuoTBFeDcOJvzVVECIQDErGxzVcXiegnXGE66\naoMTGTv0HvDbFKO7aosMXpNEnw==\n-----END CERTIFICATE-----",
		},
		{
			Path: org3Path + "/ca/ca.key",
			Data: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEINrM6uqsz5fypxSVGCoFiazpXFn8yuuM9wkP/AAo6UXioAoGCCqGSM49\nAwEHoUQDQgAEnjEQUCrUD7ftV5y8uc6xASiq9rJgSDCHMHZO5Xc/2iKO5aAoC2P+\nvz61Bb95AX/4484D0LwMzlUYdqbnKpVHoA==\n-----END EC PRIVATE KEY-----",
		},
		{
			Path: org4Path + "/ca/ca.crt",
			Data: "-----BEGIN CERTIFICATE-----\nMIICrzCCAlWgAwIBAgIDAmmkMAoGCCqGSM49BAMCMIGKMQswCQYDVQQGEwJDTjEQ\nMA4GA1UECBMHQmVpamluZzEQMA4GA1UEBxMHQmVpamluZzEfMB0GA1UEChMWd3gt\nb3JnNC5jaGFpbm1ha2VyLm9yZzESMBAGA1UECxMJcm9vdC1jZXJ0MSIwIAYDVQQD\nExljYS53eC1vcmc0LmNoYWlubWFrZXIub3JnMB4XDTIxMDgwODExMTAyM1oXDTMx\nMDgwNjExMTAyM1owgYoxCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRAw\nDgYDVQQHEwdCZWlqaW5nMR8wHQYDVQQKExZ3eC1vcmc0LmNoYWlubWFrZXIub3Jn\nMRIwEAYDVQQLEwlyb290LWNlcnQxIjAgBgNVBAMTGWNhLnd4LW9yZzQuY2hhaW5t\nYWtlci5vcmcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAR27NN4J4/X++0IZZKX\nCvRXF6gm/+Jm+mzVxJ9M6vzFdDIlUwKgSCK1TyJ5atsUSMz7qRcHN833e4VToDB3\nr67Zo4GnMIGkMA4GA1UdDwEB/wQEAwIBpjAPBgNVHSUECDAGBgRVHSUAMA8GA1Ud\nEwEB/wQFMAMBAf8wKQYDVR0OBCIEILlTxue+HpcO+Fl0WERZK/PF/7Ukc2uw0De6\nOx449l6OMEUGA1UdEQQ+MDyCDmNoYWlubWFrZXIub3Jngglsb2NhbGhvc3SCGWNh\nLnd4LW9yZzQuY2hhaW5tYWtlci5vcmeHBH8AAAEwCgYIKoZIzj0EAwIDSAAwRQIg\nBVGA2cUBpVYBJMKL/PCVj8mrVRgaXf0z3wS1ghGeqyICIQC3QqBmUpj8oLUCq7gM\nbI0/474oPezTdunB0oYy7zPKvg==\n-----END CERTIFICATE-----",
		},
		{
			Path: org4Path + "/ca/ca.key",
			Data: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIEi0YPrNlYVSnTzbZAjj3xxWRvyUpuvd4w/5xErV/DWUoAoGCCqGSM49\nAwEHoUQDQgAEduzTeCeP1/vtCGWSlwr0VxeoJv/iZvps1cSfTOr8xXQyJVMCoEgi\ntU8ieWrbFEjM+6kXBzfN93uFU6Awd6+u2Q==\n-----END EC PRIVATE KEY-----\n",
		},
		{
			Path: org5Path + "/ca/ca.crt",
			Data: "-----BEGIN CERTIFICATE-----\nMIICrzCCAlWgAwIBAgIDAnAfMAoGCCqGSM49BAMCMIGKMQswCQYDVQQGEwJDTjEQ\nMA4GA1UECBMHQmVpamluZzEQMA4GA1UEBxMHQmVpamluZzEfMB0GA1UEChMWd3gt\nb3JnNS5jaGFpbm1ha2VyLm9yZzESMBAGA1UECxMJcm9vdC1jZXJ0MSIwIAYDVQQD\nExljYS53eC1vcmc1LmNoYWlubWFrZXIub3JnMB4XDTIxMDgwODExMTAyM1oXDTMx\nMDgwNjExMTAyM1owgYoxCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRAw\nDgYDVQQHEwdCZWlqaW5nMR8wHQYDVQQKExZ3eC1vcmc1LmNoYWlubWFrZXIub3Jn\nMRIwEAYDVQQLEwlyb290LWNlcnQxIjAgBgNVBAMTGWNhLnd4LW9yZzUuY2hhaW5t\nYWtlci5vcmcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ8k/7PUzI89+TgEh+A\nPIUvb0nVwjiZDWyLm7endHoL+1bXPrb9BMOoDORikEFMgpKXWxBZ5WEl5OH60+Wz\nxF3Co4GnMIGkMA4GA1UdDwEB/wQEAwIBpjAPBgNVHSUECDAGBgRVHSUAMA8GA1Ud\nEwEB/wQFMAMBAf8wKQYDVR0OBCIEIOES4WoiGjoOHv+JdRstcNShwU8zp5lxXRwN\nbn1r655PMEUGA1UdEQQ+MDyCDmNoYWlubWFrZXIub3Jngglsb2NhbGhvc3SCGWNh\nLnd4LW9yZzUuY2hhaW5tYWtlci5vcmeHBH8AAAEwCgYIKoZIzj0EAwIDSAAwRQIh\nANG61DdWMZStJNpvx9izINq2F+ZBydFXUw/Wi5eF+wLNAiBcVq6tgOudfoGVh5aE\nZ0Z9STKkwX/bz7v6IERgxHDNVg==\n-----END CERTIFICATE-----",
		},
		{
			Path: org5Path + "/ca/ca.key",
			Data: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEICuvKR2QKtEn93qoBsJTWQXuiE9OOOirUZtXpSp7xo6soAoGCCqGSM49\nAwEHoUQDQgAEPJP+z1MyPPfk4BIfgDyFL29J1cI4mQ1si5u3p3R6C/tW1z62/QTD\nqAzkYpBBTIKSl1sQWeVhJeTh+tPls8Rdwg==\n-----END EC PRIVATE KEY-----",
		},
		{
			Path: org6Path + "/ca/ca.crt",
			Data: "-----BEGIN CERTIFICATE-----\nMIICrjCCAlWgAwIBAgIDAm6LMAoGCCqGSM49BAMCMIGKMQswCQYDVQQGEwJDTjEQ\nMA4GA1UECBMHQmVpamluZzEQMA4GA1UEBxMHQmVpamluZzEfMB0GA1UEChMWd3gt\nb3JnNi5jaGFpbm1ha2VyLm9yZzESMBAGA1UECxMJcm9vdC1jZXJ0MSIwIAYDVQQD\nExljYS53eC1vcmc2LmNoYWlubWFrZXIub3JnMB4XDTIxMDgwODExMTAyM1oXDTMx\nMDgwNjExMTAyM1owgYoxCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRAw\nDgYDVQQHEwdCZWlqaW5nMR8wHQYDVQQKExZ3eC1vcmc2LmNoYWlubWFrZXIub3Jn\nMRIwEAYDVQQLEwlyb290LWNlcnQxIjAgBgNVBAMTGWNhLnd4LW9yZzYuY2hhaW5t\nYWtlci5vcmcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARhMK7j6lJF9oPgznBV\n/Y/CRVRG+63VAZz/rsXy6aOt7y7QGyuFAxzT1q+XrHFmm0Kq8re+t2f7R1D4G0vV\naVAao4GnMIGkMA4GA1UdDwEB/wQEAwIBpjAPBgNVHSUECDAGBgRVHSUAMA8GA1Ud\nEwEB/wQFMAMBAf8wKQYDVR0OBCIEIAGk9sSMH04QcanRtgjjwv6Piqth3Jj38s19\njlK2musvMEUGA1UdEQQ+MDyCDmNoYWlubWFrZXIub3Jngglsb2NhbGhvc3SCGWNh\nLnd4LW9yZzYuY2hhaW5tYWtlci5vcmeHBH8AAAEwCgYIKoZIzj0EAwIDRwAwRAIg\nArjtU5pjlt/F1wMAZngq3uU3zrb8kjo/ZQc7dnKMkbQCIFCdNyol/rYza4NpkBHv\n4uH75wnB19Jz0k8O2I1PP5u2\n-----END CERTIFICATE-----",
		},
		{
			Path: org6Path + "/ca/ca.key",
			Data: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIHWxZYJuYug7hbqkl2DeRQTYgrEJkGcbdR0JBZKC5kZmoAoGCCqGSM49\nAwEHoUQDQgAEYTCu4+pSRfaD4M5wVf2PwkVURvut1QGc/67F8umjre8u0BsrhQMc\n09avl6xxZptCqvK3vrdn+0dQ+BtL1WlQGg==\n-----END EC PRIVATE KEY-----",
		},
		{
			Path: org7Path + "/ca/ca.crt",
			Data: "-----BEGIN CERTIFICATE-----\nMIICrzCCAlWgAwIBAgIDDTuQMAoGCCqGSM49BAMCMIGKMQswCQYDVQQGEwJDTjEQ\nMA4GA1UECBMHQmVpamluZzEQMA4GA1UEBxMHQmVpamluZzEfMB0GA1UEChMWd3gt\nb3JnNy5jaGFpbm1ha2VyLm9yZzESMBAGA1UECxMJcm9vdC1jZXJ0MSIwIAYDVQQD\nExljYS53eC1vcmc3LmNoYWlubWFrZXIub3JnMB4XDTIxMDgwODExMTAyM1oXDTMx\nMDgwNjExMTAyM1owgYoxCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRAw\nDgYDVQQHEwdCZWlqaW5nMR8wHQYDVQQKExZ3eC1vcmc3LmNoYWlubWFrZXIub3Jn\nMRIwEAYDVQQLEwlyb290LWNlcnQxIjAgBgNVBAMTGWNhLnd4LW9yZzcuY2hhaW5t\nYWtlci5vcmcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ+RD86XKWesN2HawT6\nFKnL6kyo3/XI8AuXqRA9lvobl21ROc6HEONGflFHXuMOaHK/z8iZ9nkneoIJzk/u\nLUmLo4GnMIGkMA4GA1UdDwEB/wQEAwIBpjAPBgNVHSUECDAGBgRVHSUAMA8GA1Ud\nEwEB/wQFMAMBAf8wKQYDVR0OBCIEIFD4HKKjMSwUxnT32TDonWnKOlA5vzeecd03\nPfN9BlhHMEUGA1UdEQQ+MDyCDmNoYWlubWFrZXIub3Jngglsb2NhbGhvc3SCGWNh\nLnd4LW9yZzcuY2hhaW5tYWtlci5vcmeHBH8AAAEwCgYIKoZIzj0EAwIDSAAwRQIg\nZtOSOiW+bdPDeQgFwX8bB/feuHopo5+ArggoTWwBKFMCIQDvb+e1rsPjdu0OZWsv\nCXLyTXn+Q/A9hE8obbX9EExwEA==\n-----END CERTIFICATE-----",
		},
		{
			Path: org7Path + "/ca/ca.key",
			Data: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIDHg1OwJ8DnwK0Zn01ThYvyIHMKax/4LxzBw0v14ejZYoAoGCCqGSM49\nAwEHoUQDQgAEPkQ/OlylnrDdh2sE+hSpy+pMqN/1yPALl6kQPZb6G5dtUTnOhxDj\nRn5RR17jDmhyv8/ImfZ5J3qCCc5P7i1Jiw==\n-----END EC PRIVATE KEY-----",
		},
	}
}

//nolint
func initConsensusConfigs() []ConfigData {
	return []ConfigData{
		{
			Path: org1Path + "/node/consensus1/consensus1.nodeid",
			Data: "QmV9wyvnGXtKauR2MV4bLndwfS4hnHkN6RhXMmEyLyRwqq",
		},
		{
			Path: org1Path + "/node/consensus1/consensus1.sign.crt",
			Data: "-----BEGIN CERTIFICATE-----\nMIICwzCCAmigAwIBAgIDA/YHMAoGCCqGSM49BAMCMIGKMQswCQYDVQQGEwJDTjEQ\nMA4GA1UECBMHQmVpamluZzEQMA4GA1UEBxMHQmVpamluZzEfMB0GA1UEChMWd3gt\nb3JnMS5jaGFpbm1ha2VyLm9yZzESMBAGA1UECxMJcm9vdC1jZXJ0MSIwIAYDVQQD\nExljYS53eC1vcmcxLmNoYWlubWFrZXIub3JnMB4XDTIxMDgwODExMTAyM1oXDTI2\nMDgwNzExMTAyM1owgZcxCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRAw\nDgYDVQQHEwdCZWlqaW5nMR8wHQYDVQQKExZ3eC1vcmcxLmNoYWlubWFrZXIub3Jn\nMRIwEAYDVQQLEwljb25zZW5zdXMxLzAtBgNVBAMTJmNvbnNlbnN1czEuc2lnbi53\neC1vcmcxLmNoYWlubWFrZXIub3JnMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE\nmUMt1TAG87yjS/lJXBhegID/SsIHEo87rMIgVu9Ewu176DJ63EWQtj1l64q75JwF\nQMZrUQmDGRCk9fq2XpsjL6OBrTCBqjAOBgNVHQ8BAf8EBAMCAaYwDwYDVR0lBAgw\nBgYEVR0lADApBgNVHQ4EIgQgBc5xTejAim9IHGGXy+5a2c6gWlDSzp3U/xZ6Dpnt\nxGowKwYDVR0jBCQwIoAgr3R9DeJ4qxzci4sYeIls4+lvYlTdgTMCnmt7sLHKCw4w\nLwYLgSdYj2QLHo9kCwQEIDQyYmFhNWNjNjBhZTQ1MWFhOWU0NDgxMmM3ODk0YzI5\nMAoGCCqGSM49BAMCA0kAMEYCIQDkUqq6PCgd/mihArQZRsFVnC88SxVdDmaJ8jz0\nZHI6WwIhAMiopuoqrJKjpTduj+904whp5OcDTx2wHH7tty2vJwSm\n-----END CERTIFICATE-----",
		},
		{
			Path: org1Path + "/node/consensus1/consensus1.sign.key",
			Data: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIFR1bHeWHwZF3Mue/V+9fCLeXTAcB3sAH7aeBaSZlaSCoAoGCCqGSM49\nAwEHoUQDQgAEmUMt1TAG87yjS/lJXBhegID/SsIHEo87rMIgVu9Ewu176DJ63EWQ\ntj1l64q75JwFQMZrUQmDGRCk9fq2XpsjLw==\n-----END EC PRIVATE KEY-----",
		},
		{
			Path: org2Path + "/node/consensus1/consensus1.nodeid",
			Data: "QmYjXpS5RtSiScjJVxzJNUo2XdfDbSoE1BaaSQG2BWLhej",
		},
		{
			Path: org2Path + "/node/consensus1/consensus1.sign.crt",
			Data: "-----BEGIN CERTIFICATE-----\nMIICwjCCAmigAwIBAgIDDsRJMAoGCCqGSM49BAMCMIGKMQswCQYDVQQGEwJDTjEQ\nMA4GA1UECBMHQmVpamluZzEQMA4GA1UEBxMHQmVpamluZzEfMB0GA1UEChMWd3gt\nb3JnMi5jaGFpbm1ha2VyLm9yZzESMBAGA1UECxMJcm9vdC1jZXJ0MSIwIAYDVQQD\nExljYS53eC1vcmcyLmNoYWlubWFrZXIub3JnMB4XDTIxMDgwODExMTAyM1oXDTI2\nMDgwNzExMTAyM1owgZcxCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRAw\nDgYDVQQHEwdCZWlqaW5nMR8wHQYDVQQKExZ3eC1vcmcyLmNoYWlubWFrZXIub3Jn\nMRIwEAYDVQQLEwljb25zZW5zdXMxLzAtBgNVBAMTJmNvbnNlbnN1czEuc2lnbi53\neC1vcmcyLmNoYWlubWFrZXIub3JnMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE\nhoC8JLRfmlCx+CgVLznTlvLtM6yK2YpTqM1/FtSlUFaaGrBfAbVesFTvxiikHy9x\nHS7uuHeC+aVF3nphJzYmxaOBrTCBqjAOBgNVHQ8BAf8EBAMCAaYwDwYDVR0lBAgw\nBgYEVR0lADApBgNVHQ4EIgQgERRq2bXQKeEh9ciY+0vmhsz3meFaHDYqBg+jgJgz\nPPUwKwYDVR0jBCQwIoAgrbAqfTsMzJdI78hY/CfVg2gGK0/GN2sHoySy9qZp/qYw\nLwYLgSdYj2QLHo9kCwQEIDQzZWEwYjk3YTgyOTQ1NDQ5MTYzMzQ4NTg1YWZmMTlj\nMAoGCCqGSM49BAMCA0gAMEUCIQDBxAtEz+4nnV1VFs3wDN6iuNEb+HlbKvfHecw4\njAnusgIgQwan7KhhO48mYEKHhTddWtV3gvtnXSL8tALLPAtji0Y=\n-----END CERTIFICATE-----",
		},
		{
			Path: org2Path + "/node/consensus1/consensus1.sign.key",
			Data: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEINjXNbCuEzM1VZxRfI0X5KbFNfIUgqkGcrdpsh+MzvFMoAoGCCqGSM49\nAwEHoUQDQgAEhoC8JLRfmlCx+CgVLznTlvLtM6yK2YpTqM1/FtSlUFaaGrBfAbVe\nsFTvxiikHy9xHS7uuHeC+aVF3nphJzYmxQ==\n-----END EC PRIVATE KEY-----",
		},
		{
			Path: org3Path + "/node/consensus1/consensus1.nodeid",
			Data: "QmYhNgL59EQriiojax98a8HQnB4DPqdN44eRy3RCdgbNPn",
		},
		{
			Path: org3Path + "/node/consensus1/consensus1.sign.crt",
			Data: "-----BEGIN CERTIFICATE-----\nMIICwTCCAmigAwIBAgIDBka5MAoGCCqGSM49BAMCMIGKMQswCQYDVQQGEwJDTjEQ\nMA4GA1UECBMHQmVpamluZzEQMA4GA1UEBxMHQmVpamluZzEfMB0GA1UEChMWd3gt\nb3JnMy5jaGFpbm1ha2VyLm9yZzESMBAGA1UECxMJcm9vdC1jZXJ0MSIwIAYDVQQD\nExljYS53eC1vcmczLmNoYWlubWFrZXIub3JnMB4XDTIxMDgwODExMTAyM1oXDTI2\nMDgwNzExMTAyM1owgZcxCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRAw\nDgYDVQQHEwdCZWlqaW5nMR8wHQYDVQQKExZ3eC1vcmczLmNoYWlubWFrZXIub3Jn\nMRIwEAYDVQQLEwljb25zZW5zdXMxLzAtBgNVBAMTJmNvbnNlbnN1czEuc2lnbi53\neC1vcmczLmNoYWlubWFrZXIub3JnMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE\n2Iu8uxI0gYeeIgvm/lij8WGqoV9IsRJx5XEvRFYQkvwdtarXHK3/SlxVjsCOCm/7\nm+7VjM0vuJZfhVSPIWiPNaOBrTCBqjAOBgNVHQ8BAf8EBAMCAaYwDwYDVR0lBAgw\nBgYEVR0lADApBgNVHQ4EIgQgR3z3g2CQ1Z7hW11GBaBIZoD41nhnMBDKLMhjWz1N\nZhMwKwYDVR0jBCQwIoAg5ISkKCgl9e3ocPhLd+x4Qou09tUCMehIkdN+TX/OqFAw\nLwYLgSdYj2QLHo9kCwQEIDVmMjk0YWE1OWUzYzRiZGU4NWE4YTc2NDcyM2Y1N2Vk\nMAoGCCqGSM49BAMCA0cAMEQCIGi70+YHXJ+zFXxsmqzU7+48OH4WpXo8YWax3tUr\nRhbtAiBC0cEjHergze2j+jNFOWz60GrnM0VrBu9VZ2b4Spk33g==\n-----END CERTIFICATE-----",
		},
		{
			Path: org3Path + "/node/consensus1/consensus1.sign.key",
			Data: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIDGabYndxxkxkdzS8RFrCPWKECpaDhGv6lO3OCnq/UEeoAoGCCqGSM49\nAwEHoUQDQgAE2Iu8uxI0gYeeIgvm/lij8WGqoV9IsRJx5XEvRFYQkvwdtarXHK3/\nSlxVjsCOCm/7m+7VjM0vuJZfhVSPIWiPNQ==\n-----END EC PRIVATE KEY-----",
		},
		{
			Path: org4Path + "/node/consensus1/consensus1.nodeid",
			Data: "Qmd6RRKw83sQrf4oZJEhuhouz48eu9BT1nLKNGqKcpD6LL",
		},
		{
			Path: org4Path + "/node/consensus1/consensus1.sign.crt",
			Data: "-----BEGIN CERTIFICATE-----\nMIICwjCCAmigAwIBAgIDC0fVMAoGCCqGSM49BAMCMIGKMQswCQYDVQQGEwJDTjEQ\nMA4GA1UECBMHQmVpamluZzEQMA4GA1UEBxMHQmVpamluZzEfMB0GA1UEChMWd3gt\nb3JnNC5jaGFpbm1ha2VyLm9yZzESMBAGA1UECxMJcm9vdC1jZXJ0MSIwIAYDVQQD\nExljYS53eC1vcmc0LmNoYWlubWFrZXIub3JnMB4XDTIxMDgwODExMTAyM1oXDTI2\nMDgwNzExMTAyM1owgZcxCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRAw\nDgYDVQQHEwdCZWlqaW5nMR8wHQYDVQQKExZ3eC1vcmc0LmNoYWlubWFrZXIub3Jn\nMRIwEAYDVQQLEwljb25zZW5zdXMxLzAtBgNVBAMTJmNvbnNlbnN1czEuc2lnbi53\neC1vcmc0LmNoYWlubWFrZXIub3JnMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE\nfoZ9HIS3zD5nnqAxWCm3zdSngucmjLWfe1hntZCCNzjkU55H+Z3X4yu0eRna50BX\npMGXTcGmWucuO5pu3N6+kKOBrTCBqjAOBgNVHQ8BAf8EBAMCAaYwDwYDVR0lBAgw\nBgYEVR0lADApBgNVHQ4EIgQgTYHQKnRw3o9hpFpq/I14nU7xWc4Y+1yzXLsi9zcl\nk+owKwYDVR0jBCQwIoAguVPG574elw74WXRYRFkr88X/tSRza7DQN7o7Hjj2Xo4w\nLwYLgSdYj2QLHo9kCwQEIGZjNzMwYTBmM2U3MjQxZDFiMTE3M2E0ODk3YWY5NmU3\nMAoGCCqGSM49BAMCA0gAMEUCIQDhXvp/mzTyNTcJlYjYGm1NJERT87oAloNcZDzs\nVCwZhQIgJ1gw02ZRj8fsNkC9EVZGx7nzTGjiiXbAiL2hz7FkMr8=\n-----END CERTIFICATE-----",
		},
		{
			Path: org4Path + "/node/consensus1/consensus1.sign.key",
			Data: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIGClfvUgTIYeTVWUHgycIOb++YWPCqG9mfI6wfnLL2yqoAoGCCqGSM49\nAwEHoUQDQgAEfoZ9HIS3zD5nnqAxWCm3zdSngucmjLWfe1hntZCCNzjkU55H+Z3X\n4yu0eRna50BXpMGXTcGmWucuO5pu3N6+kA==\n-----END EC PRIVATE KEY-----",
		},
		{
			Path: org5Path + "/node/consensus1/consensus1.nodeid",
			Data: "QmNVStQFk7uPpaBGLr1eZABYfyazfMGTQ6SrXVniZ74W6i",
		},
		{
			Path: org5Path + "/node/consensus1/consensus1.sign.crt",
			Data: "-----BEGIN CERTIFICATE-----\nMIICwjCCAmigAwIBAgIDCwL7MAoGCCqGSM49BAMCMIGKMQswCQYDVQQGEwJDTjEQ\nMA4GA1UECBMHQmVpamluZzEQMA4GA1UEBxMHQmVpamluZzEfMB0GA1UEChMWd3gt\nb3JnNS5jaGFpbm1ha2VyLm9yZzESMBAGA1UECxMJcm9vdC1jZXJ0MSIwIAYDVQQD\nExljYS53eC1vcmc1LmNoYWlubWFrZXIub3JnMB4XDTIxMDgwODExMTAyM1oXDTI2\nMDgwNzExMTAyM1owgZcxCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRAw\nDgYDVQQHEwdCZWlqaW5nMR8wHQYDVQQKExZ3eC1vcmc1LmNoYWlubWFrZXIub3Jn\nMRIwEAYDVQQLEwljb25zZW5zdXMxLzAtBgNVBAMTJmNvbnNlbnN1czEuc2lnbi53\neC1vcmc1LmNoYWlubWFrZXIub3JnMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE\nMMBBc6nTYJ2SnGPHhMapSL26tEIhYleBAeIdSBbcHlVnfjT7chCVkBPqFok3EA7y\n4aEImqw8dg+42mfXXOV9sKOBrTCBqjAOBgNVHQ8BAf8EBAMCAaYwDwYDVR0lBAgw\nBgYEVR0lADApBgNVHQ4EIgQgQeS23Omao9EYuEe4qKbiV3KryndwGD7vzXlhkMN+\nJiAwKwYDVR0jBCQwIoAg4RLhaiIaOg4e/4l1Gy1w1KHBTzOnmXFdHA1ufWvrnk8w\nLwYLgSdYj2QLHo9kCwQEIDMwYjAyZmMzYWUwYjRhMzFiNTFjNGFlNmIyZGNkNzhk\nMAoGCCqGSM49BAMCA0gAMEUCIF4DVqza3BQgqdmkHiDIMQ26hbKkhXJuoFB81AJR\niSsnAiEAwKiW/8gYo/iLBCAHzBRYG0ByXK/FkrJkN2V6N/qX+3I=\n-----END CERTIFICATE-----",
		},
		{
			Path: org5Path + "/node/consensus1/consensus1.sign.key",
			Data: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEID32Y3TeC8EQd/A+NtE11k/EZBQZSmibVWKCggVxA9LOoAoGCCqGSM49\nAwEHoUQDQgAEMMBBc6nTYJ2SnGPHhMapSL26tEIhYleBAeIdSBbcHlVnfjT7chCV\nkBPqFok3EA7y4aEImqw8dg+42mfXXOV9sA==\n-----END EC PRIVATE KEY-----",
		},
		{
			Path: org6Path + "/node/consensus1/consensus1.nodeid",
			Data: "QmYQQsMAdcbkY2U1FER7ZWMhWENBNUZdhUEdSXWpp2H8AK",
		},
		{
			Path: org6Path + "/node/consensus1/consensus1.sign.crt",
			Data: "-----BEGIN CERTIFICATE-----\nMIICwjCCAmigAwIBAgIDBETkMAoGCCqGSM49BAMCMIGKMQswCQYDVQQGEwJDTjEQ\nMA4GA1UECBMHQmVpamluZzEQMA4GA1UEBxMHQmVpamluZzEfMB0GA1UEChMWd3gt\nb3JnNi5jaGFpbm1ha2VyLm9yZzESMBAGA1UECxMJcm9vdC1jZXJ0MSIwIAYDVQQD\nExljYS53eC1vcmc2LmNoYWlubWFrZXIub3JnMB4XDTIxMDgwODExMTAyM1oXDTI2\nMDgwNzExMTAyM1owgZcxCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRAw\nDgYDVQQHEwdCZWlqaW5nMR8wHQYDVQQKExZ3eC1vcmc2LmNoYWlubWFrZXIub3Jn\nMRIwEAYDVQQLEwljb25zZW5zdXMxLzAtBgNVBAMTJmNvbnNlbnN1czEuc2lnbi53\neC1vcmc2LmNoYWlubWFrZXIub3JnMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE\nT+4Cex9CpC2po7Mj7WVyoX8chbo71jqj+pQrOiRq+wkUFNGlsha+XjoYrDmqXv3I\nvKSfmQAwvRXyQhIfme81nKOBrTCBqjAOBgNVHQ8BAf8EBAMCAaYwDwYDVR0lBAgw\nBgYEVR0lADApBgNVHQ4EIgQgiWpbwjKmuWHbi+Z6wnd+DHNBlQ27FwC0SpQ2KOSH\nj8owKwYDVR0jBCQwIoAgAaT2xIwfThBxqdG2COPC/o+Kq2HcmPfyzX2OUraa6y8w\nLwYLgSdYj2QLHo9kCwQEIDMzM2EzYmQxZGRhNzQ4MWY5ZmJkMzU2Yzg1M2YwNmJm\nMAoGCCqGSM49BAMCA0gAMEUCIHwkVaMJicuGZN1wph8P6XFMEe34arizMfs0rit8\nA3+uAiEAgOJGByMpjO7sm3Zwfr8miGSp8OOMmC6HLVvEGXm9YAY=\n-----END CERTIFICATE-----",
		},
		{
			Path: org6Path + "/node/consensus1/consensus1.sign.key",
			Data: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIK5LlRNQIih358TXKWt8vcgskhMeKM9/gTMxp7ZXys7ooAoGCCqGSM49\nAwEHoUQDQgAET+4Cex9CpC2po7Mj7WVyoX8chbo71jqj+pQrOiRq+wkUFNGlsha+\nXjoYrDmqXv3IvKSfmQAwvRXyQhIfme81nA==\n-----END EC PRIVATE KEY-----",
		},
		{
			Path: org7Path + "/node/consensus1/consensus1.nodeid",
			Data: "QmcUDfpj57gJSmtapzpo2TatZSZmFfJSnbGza5cLkweESQ",
		},
		{
			Path: org7Path + "/node/consensus1/consensus1.sign.crt",
			Data: "-----BEGIN CERTIFICATE-----\nMIICwTCCAmigAwIBAgIDA15PMAoGCCqGSM49BAMCMIGKMQswCQYDVQQGEwJDTjEQ\nMA4GA1UECBMHQmVpamluZzEQMA4GA1UEBxMHQmVpamluZzEfMB0GA1UEChMWd3gt\nb3JnNy5jaGFpbm1ha2VyLm9yZzESMBAGA1UECxMJcm9vdC1jZXJ0MSIwIAYDVQQD\nExljYS53eC1vcmc3LmNoYWlubWFrZXIub3JnMB4XDTIxMDgwODExMTAyM1oXDTI2\nMDgwNzExMTAyM1owgZcxCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRAw\nDgYDVQQHEwdCZWlqaW5nMR8wHQYDVQQKExZ3eC1vcmc3LmNoYWlubWFrZXIub3Jn\nMRIwEAYDVQQLEwljb25zZW5zdXMxLzAtBgNVBAMTJmNvbnNlbnN1czEuc2lnbi53\neC1vcmc3LmNoYWlubWFrZXIub3JnMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE\n0uTHuw3tJmgB34o0Z8sJ2qnh1yCkToguKayJB9YQUeK3li87t572Gkohn2bHuqsf\nuyAUa+lfUlFb2Pihhx2/J6OBrTCBqjAOBgNVHQ8BAf8EBAMCAaYwDwYDVR0lBAgw\nBgYEVR0lADApBgNVHQ4EIgQgx8noG30DAKxg29rAoIHHsi7job+FpbhtP4yV1rUy\nSEMwKwYDVR0jBCQwIoAgUPgcoqMxLBTGdPfZMOidaco6UDm/N55x3Tc9830GWEcw\nLwYLgSdYj2QLHo9kCwQEIDUzMjFhOWNkYzg0NDQyNzVhM2Q4Zjc5ZjUzYzYwZWZk\nMAoGCCqGSM49BAMCA0cAMEQCIEoGiNnKGjh1qHd7aeCAaYTLAfK6chkk8KzZdgKQ\n2LZ6AiBAdd6brxDgo7Ki8Nr70Lto6HFU3gHjOQTVu4ZIjnZL9Q==\n-----END CERTIFICATE-----",
		},
		{
			Path: org7Path + "/node/consensus1/consensus1.sign.key",
			Data: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEICuNAq6Rs1+tsHp0EjwXAP3yrgNzZGBdiBKTV6diWG3NoAoGCCqGSM49\nAwEHoUQDQgAE0uTHuw3tJmgB34o0Z8sJ2qnh1yCkToguKayJB9YQUeK3li87t572\nGkohn2bHuqsfuyAUa+lfUlFb2Pihhx2/Jw==\n-----END EC PRIVATE KEY-----",
		},
	}
}

// ConfigData config data struct
type ConfigData struct {
	Path string
	Data string
}
