# Network Settings
net:
  auth_type: "permissionedWithCert"
  # Network provider, can be libp2p or liquid.
  # libp2p: using libp2p components to build the p2p module.
  # liquid: a new p2p module we build from 0 to 1.
  # This item must be consistent across the blockchain network.
  provider: LibP2P

  # The address and port the node listens on.
  # By default, it uses 0.0.0.0 to listen on all network interfaces.
  listen_addr: /ip4/0.0.0.0/tcp/10010

  # Max stream of a connection.
  # peer_stream_pool_size: 100

  # Max number of peers the node can connect.
  # max_peer_count_allow: 20

  # The strategy for eliminating node when the count of connecting peers reach the max value.
  # It could be: 1 Random, 2 FIFO, 3 LIFO. The default strategy is LIFO.
  # peer_elimination_strategy: 3

  # The seeds peer list used to join in the network when starting.
  # The connection supervisor will try to dial seed peer whenever the connection is broken.
  # Example ip format: "/ip4/127.0.0.1/tcp/11301/p2p/"+nodeid
  # Example dns format："/dns/cm-node1.org/tcp/11301/p2p/"+nodeid
#  seeds:
#    - "/ip4/127.0.0.1/tcp/11301/p2p/QmcQHCuAXaFkbcsPUj7e37hXXfZ9DdN7bozseo5oX4qiC4"
#    - "/ip4/127.0.0.1/tcp/11302/p2p/QmeyNRs2DwWjcHTpcVHoUSaDAAif4VQZ2wQDQAUNDP33gH"
#    - "/ip4/127.0.0.1/tcp/11303/p2p/QmXf6mnQDBR9aHauRmViKzSuZgpumkn7x6rNxw1oqqRr45"
#    - "/ip4/127.0.0.1/tcp/11304/p2p/QmRRWXJpAVdhFsFtd9ah5F4LDQWFFBDVKpECAF8hssqj6H"
#    #    - "/ip4/127.0.0.1/tcp/11305/p2p/QmVSCXfPweL1GRSNt8gjcw1YQ2VcCirAtTdLKGkgGKsHqi"
#    #    - "/ip4/127.0.0.1/tcp/11306/p2p/QmPpx5dTZ4A1GQ9a4nsSoMJ72AtT3VDgcX2EVKAFxJUHb1"
#    #    - "/ip4/127.0.0.1/tcp/11307/p2p/QmVGSXfz6vgXBjWiZh5rV8T5nutevvunHAfEoe6Sh5Xcyx"

  # Network tls settings.
  tls:
    # Enable tls or not. Currently it can only be true...
    enabled: true

    # TLS private key file path.
    priv_key_file: ./config/wx-org5.chainmaker.org/certs/node/consensus1/consensus1.tls.key

    # TLS Certificate file path.
    cert_file: ./config/wx-org5.chainmaker.org/certs/node/consensus1/consensus1.tls.crt

    # Qmcg2zay8QDykQnoePf8aytsRqiEFKwbS91Uj2zcRnqUwv
    # The blacklisted peers in p2p network.
    # blacklist:
    # The addresses in blacklist.
    # The address format can be ip or ip+port.
    # addresses:
    #   - "127.0.0.1:11301"
    #   - "192.168.1.8"

    # The node ids in blacklist.
    # node_ids:
  #   - "QmeyNRs2DwWjcHTpcVHoUSaDAAif4VQZ2wQDQAUNDP33gH"
  # custom trust roots
  custom_trust_roots:
    - chain_id: "chain1"
      trust_roots:
        - "./config/wx-org5.chainmaker.org/certs/ca/wx-org1.chainmaker.org/ca.crt"
        - "./config/wx-org5.chainmaker.org/certs/ca/wx-org2.chainmaker.org/ca.crt"
        - "./config/wx-org5.chainmaker.org/certs/ca/wx-org3.chainmaker.org/ca.crt"
        - "./config/wx-org5.chainmaker.org/certs/ca/wx-org4.chainmaker.org/ca.crt"
        - "./config/wx-org5.chainmaker.org/certs/ca/wx-org5.chainmaker.org/ca.crt"